name: CMake-static-build-32

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout Triton
      uses: actions/checkout@v3
      with:
        repository: gmh5225/Triton
        path: Triton
  
    - name: Checkout 3rdparty
      uses: actions/checkout@v3
      with:
        repository: gmh5225/Triton-static-3rdparty
        path: Triton/Triton-static-3rdparty
  
    - name: Build
      run: |
        cmake -B build -A Win32 -DCMAKE_BUILD_TYPE=Release -DMSVC_STATIC=on -DBOOST_INTERFACE=off -DPYTHON_BINDINGS=off -DZ3_INCLUDE_DIRS="Triton-static-3rdparty/libz3/include" -DZ3_LIBRARIES="Triton-static-3rdparty/libz3/X86/libz3.lib" -DCAPSTONE_INCLUDE_DIRS="Triton-static-3rdparty/capstone/include" -DCAPSTONE_LIBRARIES="Triton-static-3rdparty/capstone/X86/capstone.lib" -DBUILD_SHARED_LIBS=off Triton
        cmake --build build --config Release --parallel
        
    - name: Copy SDK
      run: |
        mkdir build\include\triton
        copy Triton\src\libtriton\includes\triton\*.* build\include\triton
        copy build\src\libtriton\includes\triton\*.* build\include\triton
        mkdir build\lib
        copy build\src\libtriton\Release\*.* build\lib
        
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: libtriton-32
        path: |
          build/include/*
          build/lib/*
      
